### ISSUE TITLE
Relay on a static API for generating the resolves in memory

### ISSUE THREAD

**Issue by b1zzu** [aerogear/graphql-testx#10]
In order to source the resolvers and type definitions, we heavy really on the fact that graphback will not change the project structure.

**Potential changes of graphback that will break graphql-testx:**
* Resolvers/typedefs requires new modules (relative, absolute) 
* Resolvers get reorganized in a new structure
* Resolvers requires more objects from the context or the context structure change
* ... do we have more?

graphql-testx should completely really on information coming from graphback and not copy and paste code from the template.

**Comment by wtrocki** [comment]
@b1zzu We are working on new architecture with more details available soon. For the moment I would focus more on the test part of things and minimize the graphback oriented work

**Comment by b1zzu** [comment]
Starting from graphback `0.10.0-dev1` is possible to create runtime resolvers without parsing the typescript code, this means that we could drop the `sourceModule` function. 

https://github.com/aerogear/graphback/pull/378

**Comment by b1zzu** [comment]
Close in favor of #66
