### ISSUE TITLE
Refactoring TestxServer constructor 

### ISSUE THREAD

**Issue by b1zzu** [aerogear/graphql-testx#103]
As testx grows the TestxServer should become more configurabel and allow the user to pass multiple options (Ex: #100 #80 #97 )

I've two approaches in my mind:

#### 1. Add options argument to the current constructor

> The names of the options are just an example

```ts
new TestxServer({
  schema: `type Task { ... } `
  port: 4040,
  service: new CRUDResolver(),
  ...
})
```

#### 2. Outsource the bootstrap in a helper function before creating the TestxServer

```ts
function bootstrapTestxServer(options) {
   // do bootstrap stuff
  return new TestxServer(knexClient, dataProvider, crudService, ...);
}

const server = bootstrapTestxServer({ ... });
```

**Comment by b1zzu** [comment]
@vinifarias wdyt?

**Comment by vinifarias** [comment]
@b1zzu I like the first option because it keeps things simple and clear to the user, but I would like the second option if we need to do some processing of the options.

**Comment by b1zzu** [comment]
@vinifarias I agree to the first option will look nicer
