### ISSUE TITLE
Master releases are picked by renovate

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphql-testx#128]
Probably missing tag.

**Comment by b1zzu** [comment]
The master releases have the tag `dev` is it a problem for renovate?
![image](https://user-images.githubusercontent.com/7964685/70696326-bf2fc200-1cc3-11ea-9443-0306fd7518f9.png)

**Comment by wtrocki** [comment]
I just noted that we getting updates: 
https://github.com/aerogear/offix/pull/297

However, I do not see other releases coming so this was just single release done by mistake
