### ISSUE TITLE
Create an example that use subscriptions

### ISSUE THREAD

**Issue by b1zzu** [aerogear/graphql-testx#13]
Because Graphback offers subscription fi we have extended Graphback correctly than also Testx could be used to thest subscription out of the box, let's create an example to prove and showcase it.

**Comment by b1zzu** [comment]
Given the current development, it's best to way for this issue before going on #75

**Comment by psturc** [comment]
@b1zzu I'm working on something else now, so I'll unassign myself from this issue and get back to it if it's still up for grabs

**Comment by b1zzu** [comment]
I really appreciate help, so if you want to continue working on this issue I can ping again once we close the #75 issue

**Comment by vinifarias** [comment]
Resolved by #88
