### ISSUE TITLE
Add Stop and Clean methods to the TestxServer API

### ISSUE THREAD

**Issue by b1zzu** [aerogear/graphql-testx#14]
The `TestxServer` should expose two additional methods:
* `stop()` to stop the server during test execution and then run `start()` to resume it
  > `stop() -> start()` should not remove the data stored inside the datase
* `clean()` (or any other names) to clean the database

**Comment by vinifarias** [comment]
@b1zzu I'll implement these methods after update the code to the new version of graphback, ok ?

I'm doing the update [here](https://github.com/vinifarias/graphql-testx/tree/chore/update-graphback-to-0.9.6).

**Comment by b1zzu** [comment]
@vinifarias sure testing the new version of graphback has more priority
