### ISSUE TITLE
Update get-port to v5.1.0

### ISSUE THREAD

**Issue by b1zzu** [aerogear/graphql-testx#152]
The new version of the get-port module has some braking changes that break the tests, we need to investigate these changes and fix them in order to update to the latest version. 

#139

**Comment by darahayes** [comment]
Looks like the latest version of get-port is now using a `setInterval` call to create a timer. https://github.com/sindresorhus/get-port/compare/v5.0.0...v5.1.0#diff-168726dbe96b3ce427e7fedce31bb0bc

At some point they call [`timer.unref`](https://nodejs.org/dist/latest-v12.x/docs/api/timers.html#timers_timeout_unref).

This is a Node.js specific thing that is not typically available in browser environments. When running the code in Jest, some globals such as `setInterval` are replaced by the JSDOM implementation. That implementation does not include `unref`. See this issue here: https://github.com/facebook/jest/issues/1909#issuecomment-252981401

**Comment by b1zzu** [comment]
I see, but I'm not sure that setting the testEnvironment to node is a good choice. Is there maybe another solution for this?

**Comment by darahayes** [comment]
Yes the test that's failing is `offline.test.ts` which is testing some behaviours of Offix so presumably we cannot set `testEnvironment` to `node`. We can either:

* Set up the TestX server in a separate node process in a similar way to the karma tests.
* Stop using `get-port`
* Open a PR/issue to `get-port` suggesting that they change this line https://github.com/sindresorhus/get-port/blob/609ac44e8508c6e71baad48d080134bad7f15189/index.js#L56 to something like `if (timer.unref) { timer.unref() }`
* extend/override the default JSDOM environment with mocks for the timers APIs

If we look at the following documentation: https://jestjs.io/docs/en/configuration.html#testenvironment-string

They have some example code of how to create/extend an environment. We would follow that example but we would extend the `https://www.npmjs.com/package/jest-environment-jsdom` environment and then reassign all of the global timer functions like `setInterval`, `setImmediate`, `setTimeout` etc. It might be possible to reassign those using [`lolex`](https://github.com/sinonjs/lolex#faking-the-native-timers) which is already used internally by jest to mock timers for Node.

I think the overall solution would look something like this:

```js
const JSDomEnvironment = require('jest-environment-jsdom');
const lolex = require('lolex');

class JSDomEnvironmentWithNodeTimers extends JSDomEnvironment {
  constructor(config, context) {
    super(config, context);
    this.testPath = context.testPath;
    this.docblockPragmas = context.docblockPragmas;
  }

  async setup() {
    await super.setup();
    this.clock = lolex.install(); // mocks all the global timers
  }

  async teardown() {
    this.clock.uninstall() // tear down the global timers
    await super.teardown();
  }

  runScript(script) {
    return super.runScript(script);
  }
}

module.exports = JSDomEnvironmentWithNodeTimers;
```

I'm not 100% sure if it will work but it might be worth trying?

**Comment by b1zzu** [comment]
* Adding a new JSDomEnvironment is definitely overkilling for just an example, we need to keep it simple
* I would like to avoid doing the same thing we are doing in karma because all the point of using jest was to not doing it like karma
* Using something different from `get-port` could be a valid solution, also never updating it can be another solution :sweat_smile: 
* Open the PR/Issue to `get-port` will be my preferred way, at least we should give it a try

wdyt?

**Comment by b1zzu** [comment]
@darahayes btw this is a low priority issue, the project is perfectly working with the old version
