### ISSUE TITLE
Error in getDatabaseSchema method

### ISSUE THREAD

**Issue by vinifarias** [aerogear/graphql-testx#69]
[Here](https://github.com/aerogear/graphql-testx/blob/master/src/index.ts#L71)  _'task'_ is being passed as a parameter to `this.dbConnection`, I think that should be passed the `table`.

**Comment by b1zzu** [comment]
@jhellar was it supposed to be table right?

**Comment by jhellar** [comment]
yes, that is a bug, should be `table` var, will fix it
