### ISSUE TITLE
Realtime mocking using testx

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphql-testx#7]
There are numerous mocking solutions that provide out of the box API, however they do not provide actual storage. Mutations are not stored.
To enable better resting for cases where data that is being sent to server needs to be returned 
we can support InMemoryDatabase use cases.

Graphback team is going to work on splitting the generation process so it can use any database abstraction. TestX can benefit from that buy utilizing in-memory layer.

What are the benefits of that:

- Testing complexity and performance of clear GraphQL layer.
How particular schema behaves without database

- Testing various frontend use cases by running service in the same process.

**Comment by wtrocki** [comment]
Ref: https://github.com/aerogear/graphback/issues/375

**Comment by b1zzu** [comment]
@wojta I'm closing this issue in favor of #10 and #22
